pipeline:
    docker:
        image: plugins/docker
        dockerfile: Dockerfile
        repo: sirboops/squid
        tags: [4.1, latest]
        experimental: true
        squash: true
        secrets: [ docker_username, docker_password ]
